#6 Program throws exception when there is unsupported file type. Fixed naming scheme.
mcic20/text_file_to_ui pull request #7
Opened 2023-04-26 08:49 UTC by mcic20

2023-04-26 09:17 UTC, mislavmatijevic requested changes
Postoje dvije pogreške koje bi trebalo ispraviti:
- ukloniti predprocesorske naredbe u potpunosti i testirati rad try-catcha na oba načina kompajla
- iskakanje message boxa prebaciti iz kôda `UserParsera` u kôd forme

2023-04-26 09:17 UTC, mislavmatijevic commented on text_file_to_ui/text_file_to_ui/Form1.cs
> +                if (a.Role == "student")
"Fixed naming scheme" dio ovog commita bi trebao ići obavezno u zaseban commit! Težimo držati commitove minimalnima, da samo pokrivaju jednu (logičku) promjenu. Imenovanje i exception su dvije potpuno različite stvari. Za imenovanje se čak može stvoriti i vlastiti issue.

2023-04-26 09:17 UTC, mislavmatijevic commented on text_file_to_ui/text_file_to_ui/UserParser.cs
> +#endif
Uh, uh. Ovo izbjegavamo pod svaku cijenu, osim recimo kada iz različitih direktorija čitamo neke konfiguracije u Debug i Release načinu rada. Dakle, ovo mora van, a softver se s neispravnim datotekama treba testirati i u jednom i u drugom načinu rada (gore se mijenjaju kod zelenog "Play" gumba).

Inače, za `try` block bi bilo najbolje da obuhvaća samo onu jednu liniju gdje očekujemo da će program puknuti. Npr., u ovom slučaju možemo dodati još jednu klasu UserFileValidator koja baci exception "UserFileInvalidException" ako u datoteci ne postoje svi traženi atributi ("Ime", "Prezime" itd.).
Vlastite Exceptione stvaramo kao najnormalnije klase, ali da nasljeđuju Exception klasu:
(`class UserFileInvalidException : Exception {...`). Probaj to napraviti samostalno.

2023-04-26 09:17 UTC, mislavmatijevic commented on text_file_to_ui/text_file_to_ui/UserParser.cs
> +#endif
Ponovo, ovo želimo zaboraviti. Try-catch mora biti najnormalniji dio kôda.

2023-04-26 09:17 UTC, mislavmatijevic commented on text_file_to_ui/text_file_to_ui/UserParser.cs
> +                    return null;
Ovo je dobro. Jedino, tu postoji jedna mini-arhitekturalna pogreška. Naime, ako već ova metoda vraća null, onda nije njezina odgovornost i stvoriti MessageBox, već neka njega stvara netko tko bi imao odgovornost obavijestiti korisnika o pogrešci.
Konkretno, budući da je MessageBox usko vezan uz grafičko sučelje, na formi treba stvoriti MessageBox ako je User bio null (kod provjere u formi `if (a != null)` dodati `else` i ovaj MessageBox).

Ima jedan vrlo bitan razlog zašto tako razmišljati. Recimo da sutra odlučimo isti ovaj program napraviti za Mac/Linux/konzolu. Ako ovako nonšalantno "pucamo" MessageBoxove (usko vezane uz OS Windows) u klasama poslovne logike (ova klasa stvara iz `readera` pravi objekt `User`), morat ćemo za te druge platforme prolaziti kroz cijelu bazu kôda i tražiti sva mjesta gdje stvaramo MessageBox.
Međutim, ako su nam svi MessageBoxovi samo na onome što je ionako usko vezano uz Windows (a to su Windows forme), onda smo sigurni da je ovaj kôd u klasama potpuno cross-platform i da su jedine ovisnosti na Windowse forme koje ionako idemo mijenjati za neke Mac/Linux prozore ili konzolnu aplikaciju. Tada je kôd **ponovno iskoristiv** što nam je uvijek jako bitno.

Zbog toga težimo forme (sloj korisničkog sučelja) držati minimalnim što se kôda poslovne logike tiče (zato stvaramo mnogo klasa), ali opet težimo na njega svaliti sve što ima veze s grafičkim sučeljem, poput skočnih MessageBoxova.

2023-04-27 09:26 UTC, mislavmatijevic requested changes
Žap mi je što nisam ranije odgovorio, nisam imao vremena.
Uglavnom, ima još malo prostora za poboljšanje. Za tako dobrog studenta, šteta bi bilo ostaviti ovo malo rješenje na ičemu manjem od savršenstva.

2023-04-27 09:26 UTC, mislavmatijevic commented on text_file_to_ui/text_file_to_ui/UserParser.cs
> +              //  }
Nisam baš oduševljen komentiranjem kôda. Kôd ili koristimo ili ne, zakomentirani kôd samo govori "nikada me nitko neće maknuti".

2023-04-27 09:26 UTC, mislavmatijevic commented on text_file_to_ui/text_file_to_ui/Form1.cs
> +            }
Od svega označenoga, samo je metoda `UserParse` opasna za izbacivanje exceptiona. Sve ostalo ne može puknuti.
Stoga, bespotrebno opterećujemo `try` blok i kôd, smanjena je čitljivost zbog jednog taba više itd.

Moj savjet: neka UserParse metoda try-catcha exception. Ako je bio exception (datoteka nije otvorena ili što već), u redu, neka `UserParse` vrati 'null'. A forma, ona ako je dobila 'null', ispisuje error-MessageBox, a ako je dobila objekt korisnika najnormalnije odrađuje sav kôd i ispisuje korisnikove podatke.

2023-04-27 09:27 UTC, mislavmatijevic commented
Btw, ako si u Varaždinu, dođeš sutra (petak 28.4.) u jutarnjim satima (8-10h) u ured? Moj ured je FOI1, direktno iznad knjižnice. Samo na 5-10min, da uživo prokomentiramo sve :)

2023-04-27 09:54 UTC, mcic20 commented
Može, dođem u 9.

2023-04-28 08:25 UTC, merged